### ISSUE TITLE
Add saves to relief pitcher stats

### ISSUE THREAD

**Issue by dbarring** [smadigan91/discord-baseball-bot#15]
So I can obsess over Blake Parker

**Comment by smadigan91** [comment]
👍

**Comment by smadigan91** [comment]
and wins, and losses. In general I need to aggregate on the "decision" category when displaying the last whatever for a pitcher

**Comment by smadigan91** [comment]
![image](https://user-images.githubusercontent.com/2806574/41262655-1073845e-6db0-11e8-9752-f8fd769bca7f.png)

![image](https://user-images.githubusercontent.com/2806574/41262661-19c2d532-6db0-11e8-8553-438b01ca9c06.png)

closing, even added blown saves (but not for /season because they aren't available by default)
